services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_db # This should create the database, but let's make sure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dev_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      target: development
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/dev_db
    command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy before starting
volumes:
  postgres_data_dev:
