version: "3.8"

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "5001:5000" # Maps your local port 5001 to the container's 5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/dev_db
    depends_on:
      - db
    command:
      ["sh", "-c", "echo $$SQLALCHEMY_DATABASE_URI && flask run --host=0.0.0.0"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_db
    ports:
      - "5432:5432"
